# Generated by Django 5.2.5 on 2025-09-02 13:09

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_pets_alter_post_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Заголовок', max_length=50),
        ),
        migrations.AlterField(
            model_name='pets',
            name='photo',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.DeleteModel(
            name='PostCategory',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='news.category'),
        ),
    ]
